- name: "Install Rust Dependencies"
  become: true
  apt:
    name:
      - curl
      - build-essential
    state: "present"

- name: Check if cargo is installed
  shell: |
    source "$HOME/.cargo/env" > /dev/null 2>&1
    command -v cargo
  args:
    executable: /bin/bash
  register: cargo_exists
  ignore_errors: yes

- name: Download Installer
  when: cargo_exists is failed
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    force: 'yes'
  tags:
    - rust

- name: Install rust/cargo
  when: cargo_exists is failed
  shell: /tmp/sh.rustup.rs -y
  tags:
    - rust

- name: Add ~/.cargo/bin to PATH for the target user (if not already there)
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: 'export PATH="$HOME/.cargo/bin:$PATH"'
    create: yes
    insertafter: EOF
    regexp: '^export PATH="\$HOME/\.cargo/bin:\$PATH"$'
    state: present
  tags:
    - rust