- name: "Install Gamemode with lug-helper dependencies"
  become: true
  apt:
    name:
      - gamemode
      # lug-helper dependencies
      - cabextract
      - coreutils
      - curl
      - wine
      - unzip
    state: "present"

- name: "Ensure lug-helper parent directory exists"
  ansible.builtin.file:
    path: "{{ ansible_facts.user_dir }}/Installs"
    state: directory

- name: "Clone the repository for lug-helper"
  ansible.builtin.git:
    repo: 'https://github.com/starcitizen-lug/lug-helper.git'
    dest: "{{ ansible_facts.user_dir }}/Installs/lug-helper"
    clone: yes
    update: yes

- name: "Ensure .local/share/icons/hicolor/256x256/apps exists"
  ansible.builtin.file:
    path: "{{ ansible_facts.user_dir }}/.local/share/icons/hicolor/256x256/apps"
    state: directory
    mode: '0755'

- name: "Copy rsi-launcher.png to .local/share/icons"
  ansible.builtin.copy:
    src: files/rsi-launcher.png
    dest: "{{ ansible_facts.user_dir }}/.local/share/icons/hicolor/256x256/apps/rsi-launcher.png"
    mode: '0755'

- name: "Create RSI Launcher desktop file"
  ansible.builtin.copy:
    src: files/rsi-launcher.desktop
    dest: "{{ ansible_facts.user_dir }}/.local/share/applications/RSI Launcher.desktop"
    mode: '0755'