- name: Copy Krohnkite KWin Script files
  ansible.builtin.copy:
    src: krohnkite/
    dest: "{{ ansible_user_dir }}/Installs/"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    mode: '0755'
    directory_mode: '0755'

- name: Check if krohnkite is already installed
  ansible.builtin.command:
    cmd: "kpackagetool6 --type KWin/Script --list"
  register: kwin_scripts_list
  changed_when: false # This command doesn't change system state

- name: Set a fact for krohnkite installation status
  ansible.builtin.set_fact:
    krohnkite_is_installed: "{{ 'krohnkite' in kwin_scripts_list.stdout }}"

- name: Install Krohnkite KWin Script
  ansible.builtin.command:
    cmd: "kpackagetool6 -t KWin/Script -i {{ ansible_user_dir }}/Installs/krohnkite-0.9.9.2_1d7fd74.kwinscript"
  when: not krohnkite_is_installed
  changed_when: true # kpackagetool6 doesn't always signal change well

- name: Configure KWin Windows behavior
  community.general.kdeconfig:
    path: "{{ ansible_user_dir }}/.config/kwinrc"
    values:
      - group: Windows
        key: ActiveMouseScreen
        value: 'false'
      - group: Windows
        key: SeparateScreenFocus
        value: 'true'

- name: Krohnkite settings
  community.general.kdeconfig:
    path: "{{ ansible_user_dir }}/.config/kwinrc"
    values:
      - group: Script-krohnkite
        key: binaryTreeLayoutOrder
        value: '0'
      - group: Script-krohnkite
        key: cascadeLayoutOrder
        value: '0'
      - group: Script-krohnkite
        key: columnsLayoutOrder
        value: '0'
      - group: Script-krohnkite
        key: floatingLayoutOrder
        value: '0'
      - group: Script-krohnkite
        key: monocleLayoutOrder
        value: '1' # Changed to 1
      - group: Script-krohnkite
        key: noTileBorder
        value: 'true' # Set to true
      - group: Script-krohnkite
        key: quarterLayoutOrder
        value: '0'
      - group: Script-krohnkite
        key: spiralLayoutOrder
        value: '2' # Changed to 2
      - group: Script-krohnkite
        key: spreadLayoutOrder
        value: '0'
      - group: Script-krohnkite
        key: stackedLayoutOrder
        value: '0'
      - group: Script-krohnkite
        key: stairLayoutOrder
        value: '0'
      - group: Script-krohnkite
        key: threeColumnLayoutOrder
        value: '0'
      - group: Script-krohnkite
        key: tileLayoutOrder
        value: '0'

- name: Enable the KWin Script in kwinrc
  community.general.kdeconfig:
    path: "{{ ansible_user_dir }}/.config/kwinrc"
    values:
      - group: Plugins
        key: "krohnkiteEnabled"
        value: 'true'

- name: Reconfigure KWin via D-Bus to apply changes
  ansible.builtin.shell:
    cmd: "qdbus6 org.kde.KWin /KWin reconfigure"
  changed_when: true
