---
- name: "Install flatpak remotes"
  flatpak_remote:
    name: "{{ item.name }}"
    flatpakrepo_url: "{{ item.url }}"
    state: "present"
    method: "system"
  loop: "{{ flatpak_packages__remotes }}"

- name: "Install flatpak packages"
  become: true
  flatpak:
    name: "{{ flatpak_packages__packages }}"
    state: "latest"
    method: "system"