- name: "Install yubikey packages"
  become: true
  apt:
    name:
    - libpam-yubico
    - libpam-u2f
    - ykls
    - scdaemon
    # optional
    - yubikey-luks
    - yubikey-manager
    - yubikey-personalization
    state: "present"

- name: "Enable GPG agent for SSH in .bashrc"
  ansible.builtin.blockinfile:
    path: "{{ ansible_facts.user_dir }}/.bashrc"
    block: |
      export GPG_TTY="$(tty)"
      export SSH_AUTH_SOCK="/run/user/$UID/gnupg/S.gpg-agent.ssh"
      gpg-connect-agent updatestartuptty /bye > /dev/null
    marker: "# {mark} ANSIBLE MANAGED BLOCK - GPG SSH"
    state: present
    create: true # Create the file if it doesn't exist
  become: yes # Use become if the user is not the current Ansible user (e.g., if targeting another user's .bashrc)

# 700 -> Directory
# 600 -> File

- name: "Ensure .gnupg directory exists with correct permissions"
  ansible.builtin.file:
    path: "{{ ansible_facts.user_dir }}/.gnupg"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    mode: '0700'

# Notwendig wenn "yubikey-*"-packages installiert sind (custom udev rules)
- name: "Set pcsc-shared"
  ansible.builtin.blockinfile:
    path: "{{ ansible_facts.user_dir }}/.gnupg/scdaemon.conf"
    block: |
      disable-ccid
      pcsc-shared
    state: present
    create: true
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    mode: '0600'

# Restart User-GPG agent:
# > systemctl --user restart gpg-agent.service
- name: "Restart GPG agent service"
  ansible.builtin.systemd:
    name: gpg-agent.service
    state: restarted
    scope: user
  become: no

# Check if yubikey is working:
# > gpg --card-status