- name: "Install yubikey packages"
  become: true
  apt:
    name:
    - libpam-yubico
    - libpam-u2f
    - ykls
    - yubikey-luks
    - yubikey-manager
    - yubikey-personalization
    - scdaemon
    state: "present"

- name: "Enable GPG agent for SSH in .bashrc"
  ansible.builtin.blockinfile:
    path: "{{ ansible_facts.user_dir }}/.bashrc"
    block: |
      # Start GPG agent for SSH support (managed by Ansible)
      export GPG_TTY="$(tty)"
      export SSH_AUTH_SOCK="/run/user/$UID/gnupg/S.gpg-agent.ssh"
      gpg-connect-agent updatestartuptty /bye > /dev/null
    marker: "# {mark} ANSIBLE MANAGED BLOCK - GPG SSH"
    state: present
    create: true # Create the file if it doesn't exist
  become: yes # Use become if the user is not the current Ansible user (e.g., if targeting another user's .bashrc)
  become_user: "{{ ansible_user_id }}" # Ensure it modifies the target user's .bashrc